[package]
name = "algo"
version = "0.3.0"
authors = ["platformer <https://github.com/platformer>"]
license = "MIT"
description = "Beautifully typeset algorithms."
entrypoint = "algo.typ"
repository = "https://github.com/platformer/typst-algorithms"
